on: push

name: Jira Create

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Create
    steps:
    - name: Jira Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: TEST
        issuetype: Story
        summary: |
           New PR approval request for ${{ github.repository }}
        description: |
           Here is where we'd link an approval framework to reference before approving the PR in Github
        fields: '{"customFieldId=10016": "1"}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
